name: Push HTML to Windows Server

on:
  push:
    branches:
      - master

jobs:
  deploymentjob:
    name: Deploy to windows server
    runs-on: ubuntu-latest

    steps:
    - name: Checking out
      uses: actions/checkout@v4

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy/Copy to windows Server
      run: sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no hussain.html "${{ secrets.USERNAME }}@${{ secrets.IP}}:C:/inetpub/wwwroot/"
